name: release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest

    steps:
      - name: Release Please
        id: release
        uses: googleapis/release-please-action@a02a34c4d625f9be7cb89156071d8567266a2445
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          release-type: node

      - name: Checkout code
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v4

      - name: Setup Bun
        if: ${{ steps.release.outputs.release_created }}
        uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5
        with:
          bun-version: 1.2.6

      - name: Install dependencies
        if: ${{ steps.release.outputs.release_created }}
        run: bun install

      - name: Build package (ESM, CJS, types)
        if: ${{ steps.release.outputs.release_created }}
        run: bun run build

      - name: Publish to npm
        if: ${{ steps.release.outputs.release_created }}
        run: bun publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
